//arat

STATEMANAGER.SetVertexShader(D3DFVF_XYZ|D3DFVF_DIFFUSE|D3DFVF_TEX1);

//değiştir

STATEMANAGER.SetFVF(D3DFVF_XYZ|D3DFVF_DIFFUSE|D3DFVF_TEX1);

//arat

		STATEMANAGER.SaveTextureStageState(0, D3DTSS_ADDRESSU,	D3DTADDRESS_CLAMP);
		STATEMANAGER.SaveTextureStageState(0, D3DTSS_ADDRESSV,	D3DTADDRESS_CLAMP);

//değiştir

		STATEMANAGER.SaveSamplerState(0, D3DSAMP_ADDRESSU,	D3DTADDRESS_CLAMP);
		STATEMANAGER.SaveSamplerState(0, D3DSAMP_ADDRESSV,	D3DTADDRESS_CLAMP);

//arat

		STATEMANAGER.RestoreTextureStageState(0, D3DTSS_ADDRESSU);
		STATEMANAGER.RestoreTextureStageState(0, D3DTSS_ADDRESSV);

//değiştir

		STATEMANAGER.RestoreSamplerState(0, D3DSAMP_ADDRESSU);
		STATEMANAGER.RestoreSamplerState(0, D3DSAMP_ADDRESSV);